#!/bin/bash
webdir=$PWD
name="Jean Dupont"
# Changez le nom ci-dessu et le nom de domaine à votre convenance
website="https://nomdedomai.ne/" # Gardez le slash à la fin 
css="../style.css"
blogfile="2019.html"
indexfile="blogindex.html"
rssfile="rss.xml"
[ -z "$EDITOR" ] && EDITOR="vim"

[ ! -d "$webdir/blog/.drafts" ] &&
read -erp "Initialiser le blog dans $webdir ?" ask &&
	if [ "$ask" = "y" ]; then
	printf "Initialisation du système de blog..\\n"
	mkdir -pv "$webdir/blog/.drafts" || printf "Erreur. Vous n'avez peut-être pas des droits suffisants?\\n"
	echo "Options +Indexes" > "$webdir/blog/.htaccess"
else
	exit
fi

newpost() { read -erp "Donne un titre à ton post:
	" title
	echo "$title" | grep "\"" >/dev/null && printf "Les guillemets (\") ne sont pas autorisés dans les titres de post.\\n" && exit
	url="$(echo "$title" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
	echo "AddDescription \"$title\" \"$url.html\"" >> "$webdir/blog/.htaccess" || { echo "Erreur: .htaccess est-il accessible en écriture ?"; exit; }
	[ -f "$webdir/blog/.drafts/$url.html" ] && echo "Il y a déjà un brouillon ou post avec la même url ou titre." && exit
	[ -f "$webdir/blog/$url.html" ] && echo "Il y a déjà un post avec le même nom ou url." && exit
	$EDITOR "$webdir/blog/.drafts/$url.html" ;}

listandReturn() { printf "Contenu de  %s.\\n" "$1"
	ls -rc "$1" | awk -F '/' '{print $NF}' | nl
	read -erp "Choisissez une option par son numéro pour  $2, ou pressez Ctrl+c pour annuler. " number
	chosen="$(ls -rc "$1" | nl | grep -w  "$number" | awk '{print $2}')"
	basefile="$(basename "$chosen")" && base="${basefile%.*}" ;}

publish() { \
	delete
	htaccessentry=$(grep "$basefile" "$webdir/blog/.htaccess")
	realname="$(echo "$htaccessentry" | cut -d'"' -f2)"
	rssdate="$(grep "$basefile" blog/.htaccess | sed "s/.*\.html\"* *#*//g" | tr -d '\n')"
	[ -z "$rssdate" ] && rssdate="$(LC_TIME=fr_FR date '+%a, %d %b %Y %H:%M:%S %z')" # RSS date formats must comply with standards to validate. Les formats des dates RSS doivent se plier aux standards être validée.
	webdate="$(date '+%a, %d %b %Y %H:%M:%S %z')" # Mais vous pouvez mettre cette date visible sous n'importe quel format. 
	tmpdir=$(mktemp -d)
	printf "<html>\\n<head>\\n<title>%s</title>\\n<link rel='stylesheet' type='text/css' href='%s'>\\n<meta charset='utf-8'/>\\n</head>\\n<body>\\n<h1>%s</h1>\\n<small>[<a href='%s#%s'>link</a>&mdash;<a href='%s'>post seul</a>]</small>\\n%s\\n<footer>by <strong><a href='%s'>%s</a></strong></footer>\\n</body>\\n\\n</html>" "$realname" "$css" "$realname" "../$blogfile" "$base" "$basefile" "$(cat "$webdir/blog/.drafts/$basefile")" "$website" "$name" > "$webdir/blog/$basefile"
	printf "\\n<item>\\n<title>%s</title>\\n<guid>%s%s#%s</guid>\\n<pubDate>%s</pubDate>\\n<description><![CDATA[\\n%s\\n]]></description>\\n</item>\\n\\n" "$realname" "$website" "$blogfile" "$base" "$rssdate" "$(cat "$webdir/blog/.drafts/$basefile")" >  "$tmpdir/rss"
	printf "<div class='entry'>\\n<h2 id='%s'>%s</h2>\\n<small>[<a href='#%s'>lien</a>&mdash;<a href='%s'>post seul</a>]</small>\\n%s\\n<small>%s</small>\\n</div>\\n" "$base" "$realname" "$base" "blog/$basefile" "$(cat "$webdir/blog/.drafts/$basefile")" "$webdate" > "$tmpdir/html"
	printf "<li>%s &ndash; <a href=\"blog/%s\">%s</a></li>\\n" "$(date '+%Y %b %d')" "$basefile" "$realname" > "$tmpdir/index"
	sed -i "/<!-- LB -->/r $tmpdir/html" "$blogfile"
	sed -i "/<!-- LB -->/r $tmpdir/rss" "$rssfile"
	sed -i "/<!-- LB -->/r $tmpdir/index" "$indexfile"
	sed -i "/ \"$base.html\"/d" "$webdir/blog/.htaccess"
	echo "AddDescription \"$realname\" \"$basefile\" #$rssdate" >> "$webdir/blog/.htaccess"
	rm -f "$webdir/blog/.drafts/$chosen"
}

confirm() { read -erp "Voulez-vous vraiment $1 \"$base\"? (y/N) " choice && echo "$choice" | grep -i "^y$" >/dev/null || exit 1 ;}

delete() { \
	sed -i "/<item/{:a;N;/<\\/item>/!ba};/#$base<\\/guid/d" $rssfile
	sed -i "/<div class='entry'>/{:a;N;/<\\/div>/!ba};/id='$base'/d" $blogfile
	sed -i "/<li>.*<a href=\"blog\\/$base.html\">/d" $indexfile
	rm "$webdir/blog/$basefile" 2>/dev/null && printf "Old blog entry removed.\\n" ;}

revise() { awk '/^<small>\[/{flag=1;next}/<footer>/{flag=0}flag' "$webdir/blog/$chosen" > "$webdir/blog/.drafts/$basefile"
	"$EDITOR" "$webdir/blog/.drafts/$basefile"
	printf "Modification stockée dans le brouillon blog/.drafts. Vous pourrez publier quand vous le souhaitez.\\n" ;}

case "$1" in
	n*) newpost ;;
	e*) listandReturn "$webdir"/blog/.drafts/ edit && "$EDITOR" "$webdir/blog/.drafts/$chosen" ;;
	p*) listandReturn "$webdir"/blog/.drafts/ publish && publish ;;
	t*) listandReturn "$webdir"/blog/.drafts/ trash && confirm trash && rm -f "$webdir/blog/.drafts/$chosen" && sed -i "/ \"$base.html\"/d" "$webdir/blog/.htaccess" ; printf "Brouillon supprimé\\n" ;;
	d*) listandReturn "$webdir"/blog/ delete && confirm delete && delete && sed -i "/ \"$base.html\"/d" "$webdir/blog/.htaccess" ;;
	r*) listandReturn "$webdir"/blog/ revise && revise ;;
	*) printf "lb, un système de blogage par Luke Smith <luke@lukesmith.xyz>\\nUsage:\\n  lb n:\\tnouveau brouillon\\n  lb e:\\téditer un brouillon\\n  lb p:\\tpublier ou finaliser un brouillon\\n  lb r:\\tmodifier un post\\n  lb t:\\tjeter un brouillon\\n  lb d:\\tsupprimer un post\\n\\nAssurez vous d'avoir cette balise dans votre flux RSS, fichier de blog and d'index de blog:\\n\\n<!-- LB -->\\n\\nLe contenu publié s'affichera en dessous de cette balise. \\nVoir https://github.com/LukeSmithxyz/lb pour plus d'informations.\\n" ;;
esac
